function writePLY(outPath, v, f, c)
%WRITEPLY  Minimal, dependency-free ASCII PLY writer.
%   writePLY(outPath, v, f, c) writes an ASCII PLY file using only base
%   MATLAB (fopen/fprintf) so it compiles into a standalone application
%   without requiring the Lidar or Computer Vision toolboxes.
%
%   Inputs:
%     outPath - destination .ply path (char or string).
%     v       - (Nx3) vertex XYZ coordinates.
%     f       - (Mx3) 1-BASED triangle face indices, or [] for a point
%               cloud (vertices only, no faces).
%     c       - (Nx3) per-vertex RGB colour, or [] for no colour. Values
%               may be either 0-1 or 0-255; the scale is auto-detected.
%
%   Faces are written 0-based (PLY convention). Vertex order is preserved,
%   so per-vertex correspondence with the source data is retained.

    arguments
        outPath (1,1) string
        v       (:,3) double
        f       double = []
        c       double = []
    end

    nV = size(v, 1);
    hasFaces  = ~isempty(f);
    hasColour = ~isempty(c);

    if hasColour && size(c, 1) ~= nV
        error("writePLY:colourSize", ...
            "Colour array has %d rows but there are %d vertices.", size(c,1), nV);
    end
    if hasFaces && size(f, 2) ~= 3
        error("writePLY:faceSize", "Faces must be an Mx3 array.");
    end

    % Auto-detect colour scale and convert to uint8 0-255.
    if hasColour
        if max(c(:)) <= 1
            c = c * 255;
        end
        c = uint8(min(max(round(c), 0), 255));
    end

    outDir = fileparts(outPath);
    if outDir ~= "" && ~isfolder(outDir)
        mkdir(outDir);
    end

    fid = fopen(outPath, 'w');
    if fid < 0
        error("writePLY:openFailed", "Could not open '%s' for writing.", outPath);
    end
    closeFid = onCleanup(@() fclose(fid)); %#ok<NASGU>

    % --- Header ---
    fprintf(fid, "ply\n");
    fprintf(fid, "format ascii 1.0\n");
    fprintf(fid, "comment generated by writePLY (Convert3DL)\n");
    fprintf(fid, "element vertex %d\n", nV);
    fprintf(fid, "property float x\n");
    fprintf(fid, "property float y\n");
    fprintf(fid, "property float z\n");
    if hasColour
        fprintf(fid, "property uchar red\n");
        fprintf(fid, "property uchar green\n");
        fprintf(fid, "property uchar blue\n");
    end
    if hasFaces
        fprintf(fid, "element face %d\n", size(f, 1));
        fprintf(fid, "property list uchar int vertex_indices\n");
    end
    fprintf(fid, "end_header\n");

    % --- Vertices (+ optional colour) ---
    if hasColour
        % Interleave xyz and rgb: one row per vertex.
        rows = [v, double(c)]';
        fprintf(fid, "%.6f %.6f %.6f %d %d %d\n", rows);
    else
        fprintf(fid, "%.6f %.6f %.6f\n", v');
    end

    % --- Faces (0-based) ---
    if hasFaces
        fIdx = int32(f) - 1;
        fprintf(fid, "3 %d %d %d\n", fIdx');
    end
end
